import { Aluno } from '../core/models/aluno.model';

export const ALUNOSMOCK: Aluno[] = [
  {
    idaluno: 1,
    nome: 'Alisson',
    cpf: '123.456.789-00',
    status: true,
    datacriacao: new Date(),
    dataalteracao: new Date(),
    usucriacao: 'admin',
    usualteracao: 'admin',
  },
  {
    idaluno: 2,
    nome: 'Anderson',
    cpf: '987.654.321-00',
    status: true,
    datacriacao: new Date(),
    dataalteracao: new Date(),
    usucriacao: 'admin',
    usualteracao: 'admin',
  },
  {
    idaluno: 3,
    nome: 'Cleberson',
    cpf: '123.456.789-00',
    status: true,
    datacriacao: new Date(),
    dataalteracao: new Date(),
    usucriacao: 'admin',
    usualteracao: 'admin',
  },
  {
    idaluno: 4,
    nome: 'Wanderson',
    cpf: '123.456.789-00',
    status: true,
    datacriacao: new Date(),
    dataalteracao: new Date(),
    usucriacao: 'admin',
    usualteracao: 'admin',
  },
  {
    idaluno: 5,
    nome: 'Robson',
    cpf: '123.456.789-00',
    status: true,
    datacriacao: new Date(),
    dataalteracao: new Date(),
    usucriacao: 'admin',
    usualteracao: 'admin',
  },
];